// <auto-generated />
using System;
using KhairAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace KhairAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260127193059_AddStreakFieldsToStudentTarget")]
    partial class AddStreakFieldsToStudentTarget
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("KhairAPI.Models.Entities.Association", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Country")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Favicon")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Logo")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ManagerName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("PrimaryColor")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("SecondaryColor")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Subdomain")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Subdomain")
                        .IsUnique();

                    b.ToTable("Associations");
                });

            modelBuilder.Entity("KhairAPI.Models.Entities.Attendance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AssociationId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("HalaqaId")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("StudentId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AssociationId");

                    b.HasIndex("Date");

                    b.HasIndex("HalaqaId");

                    b.HasIndex("Date", "HalaqaId");

                    b.HasIndex("StudentId", "Date")
                        .IsUnique();

                    b.ToTable("Attendances");
                });

            modelBuilder.Entity("KhairAPI.Models.Entities.Halaqa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ActiveDays")
                        .HasColumnType("text");

                    b.Property<int>("AssociationId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Location")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("TimeSlot")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("AssociationId");

                    b.ToTable("Halaqat");
                });

            modelBuilder.Entity("KhairAPI.Models.Entities.HalaqaSupervisorAssignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AssignedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("AssociationId")
                        .HasColumnType("integer");

                    b.Property<int>("HalaqaId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AssociationId");

                    b.HasIndex("HalaqaId");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "HalaqaId")
                        .IsUnique();

                    b.ToTable("HalaqaSupervisorAssignments");
                });

            modelBuilder.Entity("KhairAPI.Models.Entities.HalaqaTeacher", b =>
                {
                    b.Property<int>("HalaqaId")
                        .HasColumnType("integer");

                    b.Property<int>("TeacherId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("AssignedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("AssociationId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean");

                    b.HasKey("HalaqaId", "TeacherId");

                    b.HasIndex("AssociationId");

                    b.HasIndex("HalaqaId");

                    b.HasIndex("TeacherId");

                    b.ToTable("HalaqaTeachers");
                });

            modelBuilder.Entity("KhairAPI.Models.Entities.ProgressRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AssociationId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("FromVerse")
                        .HasColumnType("integer");

                    b.Property<int>("HalaqaId")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<double>("NumberLines")
                        .HasColumnType("double precision");

                    b.Property<string>("Quality")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("StudentId")
                        .HasColumnType("integer");

                    b.Property<string>("SurahName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("TeacherId")
                        .HasColumnType("integer");

                    b.Property<int>("ToVerse")
                        .HasColumnType("integer");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("AssociationId");

                    b.HasIndex("Date");

                    b.HasIndex("HalaqaId");

                    b.HasIndex("StudentId");

                    b.HasIndex("TeacherId");

                    b.HasIndex("Date", "HalaqaId");

                    b.HasIndex("Date", "StudentId");

                    b.HasIndex("StudentId", "Date", "Type");

                    b.ToTable("ProgressRecords");
                });

            modelBuilder.Entity("KhairAPI.Models.Entities.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AssociationId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("CurrentSurahNumber")
                        .HasColumnType("integer");

                    b.Property<int>("CurrentVerse")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("GuardianName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("GuardianPhone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("IdNumber")
                        .HasColumnType("text");

                    b.Property<decimal>("JuzMemorized")
                        .HasColumnType("numeric");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("MemorizationDirection")
                        .HasColumnType("integer");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AssociationId");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("KhairAPI.Models.Entities.StudentHalaqa", b =>
                {
                    b.Property<int>("StudentId")
                        .HasColumnType("integer");

                    b.Property<int>("HalaqaId")
                        .HasColumnType("integer");

                    b.Property<int>("TeacherId")
                        .HasColumnType("integer");

                    b.Property<int>("AssociationId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("EnrollmentDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.HasKey("StudentId", "HalaqaId", "TeacherId");

                    b.HasIndex("AssociationId");

                    b.HasIndex("HalaqaId");

                    b.HasIndex("TeacherId");

                    b.HasIndex("HalaqaId", "TeacherId");

                    b.ToTable("StudentHalaqat");
                });

            modelBuilder.Entity("KhairAPI.Models.Entities.StudentTarget", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AssociationId")
                        .HasColumnType("integer");

                    b.Property<int?>("ConsolidationPagesTarget")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("CurrentStreak")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("LastStreakDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("LongestStreak")
                        .HasColumnType("integer");

                    b.Property<int?>("MemorizationLinesTarget")
                        .HasColumnType("integer");

                    b.Property<int?>("RevisionPagesTarget")
                        .HasColumnType("integer");

                    b.Property<int>("StudentId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("AssociationId");

                    b.HasIndex("StudentId")
                        .IsUnique();

                    b.ToTable("StudentTargets");
                });

            modelBuilder.Entity("KhairAPI.Models.Entities.Teacher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AssociationId")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("IdNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("JoinDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Qualification")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AssociationId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Teachers");
                });

            modelBuilder.Entity("KhairAPI.Models.Entities.TeacherAttendance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AssociationId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("HalaqaId")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("TeacherId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AssociationId");

                    b.HasIndex("Date");

                    b.HasIndex("HalaqaId");

                    b.HasIndex("TeacherId");

                    b.HasIndex("Date", "HalaqaId");

                    b.HasIndex("Date", "TeacherId");

                    b.HasIndex("TeacherId", "HalaqaId", "Date")
                        .IsUnique();

                    b.ToTable("TeacherAttendances");
                });

            modelBuilder.Entity("KhairAPI.Models.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AssociationId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("AssociationId");

                    b.HasIndex("PhoneNumber", "AssociationId")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("KhairAPI.Models.Entities.Attendance", b =>
                {
                    b.HasOne("KhairAPI.Models.Entities.Association", "Association")
                        .WithMany("Attendances")
                        .HasForeignKey("AssociationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KhairAPI.Models.Entities.Halaqa", "Halaqa")
                        .WithMany("Attendances")
                        .HasForeignKey("HalaqaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KhairAPI.Models.Entities.Student", "Student")
                        .WithMany("Attendances")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Association");

                    b.Navigation("Halaqa");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("KhairAPI.Models.Entities.Halaqa", b =>
                {
                    b.HasOne("KhairAPI.Models.Entities.Association", "Association")
                        .WithMany("Halaqat")
                        .HasForeignKey("AssociationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Association");
                });

            modelBuilder.Entity("KhairAPI.Models.Entities.HalaqaSupervisorAssignment", b =>
                {
                    b.HasOne("KhairAPI.Models.Entities.Association", "Association")
                        .WithMany()
                        .HasForeignKey("AssociationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KhairAPI.Models.Entities.Halaqa", "Halaqa")
                        .WithMany("SupervisorAssignments")
                        .HasForeignKey("HalaqaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KhairAPI.Models.Entities.User", "User")
                        .WithMany("HalaqaAssignments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Association");

                    b.Navigation("Halaqa");

                    b.Navigation("User");
                });

            modelBuilder.Entity("KhairAPI.Models.Entities.HalaqaTeacher", b =>
                {
                    b.HasOne("KhairAPI.Models.Entities.Association", "Association")
                        .WithMany("HalaqaTeachers")
                        .HasForeignKey("AssociationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KhairAPI.Models.Entities.Halaqa", "Halaqa")
                        .WithMany("HalaqaTeachers")
                        .HasForeignKey("HalaqaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KhairAPI.Models.Entities.Teacher", "Teacher")
                        .WithMany("HalaqaTeachers")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Association");

                    b.Navigation("Halaqa");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("KhairAPI.Models.Entities.ProgressRecord", b =>
                {
                    b.HasOne("KhairAPI.Models.Entities.Association", "Association")
                        .WithMany("ProgressRecords")
                        .HasForeignKey("AssociationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KhairAPI.Models.Entities.Halaqa", "Halaqa")
                        .WithMany("ProgressRecords")
                        .HasForeignKey("HalaqaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KhairAPI.Models.Entities.Student", "Student")
                        .WithMany("ProgressRecords")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KhairAPI.Models.Entities.Teacher", "Teacher")
                        .WithMany("ProgressRecords")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Association");

                    b.Navigation("Halaqa");

                    b.Navigation("Student");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("KhairAPI.Models.Entities.Student", b =>
                {
                    b.HasOne("KhairAPI.Models.Entities.Association", "Association")
                        .WithMany("Students")
                        .HasForeignKey("AssociationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Association");
                });

            modelBuilder.Entity("KhairAPI.Models.Entities.StudentHalaqa", b =>
                {
                    b.HasOne("KhairAPI.Models.Entities.Association", "Association")
                        .WithMany("StudentHalaqat")
                        .HasForeignKey("AssociationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KhairAPI.Models.Entities.Halaqa", "Halaqa")
                        .WithMany("StudentHalaqat")
                        .HasForeignKey("HalaqaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KhairAPI.Models.Entities.Student", "Student")
                        .WithMany("StudentHalaqat")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KhairAPI.Models.Entities.Teacher", "Teacher")
                        .WithMany("StudentHalaqat")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Association");

                    b.Navigation("Halaqa");

                    b.Navigation("Student");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("KhairAPI.Models.Entities.StudentTarget", b =>
                {
                    b.HasOne("KhairAPI.Models.Entities.Association", "Association")
                        .WithMany("StudentTargets")
                        .HasForeignKey("AssociationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KhairAPI.Models.Entities.Student", "Student")
                        .WithOne("Target")
                        .HasForeignKey("KhairAPI.Models.Entities.StudentTarget", "StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Association");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("KhairAPI.Models.Entities.Teacher", b =>
                {
                    b.HasOne("KhairAPI.Models.Entities.Association", "Association")
                        .WithMany("Teachers")
                        .HasForeignKey("AssociationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KhairAPI.Models.Entities.User", "User")
                        .WithOne("Teacher")
                        .HasForeignKey("KhairAPI.Models.Entities.Teacher", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Association");

                    b.Navigation("User");
                });

            modelBuilder.Entity("KhairAPI.Models.Entities.TeacherAttendance", b =>
                {
                    b.HasOne("KhairAPI.Models.Entities.Association", "Association")
                        .WithMany("TeacherAttendances")
                        .HasForeignKey("AssociationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KhairAPI.Models.Entities.Halaqa", "Halaqa")
                        .WithMany("TeacherAttendances")
                        .HasForeignKey("HalaqaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KhairAPI.Models.Entities.Teacher", "Teacher")
                        .WithMany("TeacherAttendances")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Association");

                    b.Navigation("Halaqa");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("KhairAPI.Models.Entities.User", b =>
                {
                    b.HasOne("KhairAPI.Models.Entities.Association", "Association")
                        .WithMany("Users")
                        .HasForeignKey("AssociationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Association");
                });

            modelBuilder.Entity("KhairAPI.Models.Entities.Association", b =>
                {
                    b.Navigation("Attendances");

                    b.Navigation("HalaqaTeachers");

                    b.Navigation("Halaqat");

                    b.Navigation("ProgressRecords");

                    b.Navigation("StudentHalaqat");

                    b.Navigation("StudentTargets");

                    b.Navigation("Students");

                    b.Navigation("TeacherAttendances");

                    b.Navigation("Teachers");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("KhairAPI.Models.Entities.Halaqa", b =>
                {
                    b.Navigation("Attendances");

                    b.Navigation("HalaqaTeachers");

                    b.Navigation("ProgressRecords");

                    b.Navigation("StudentHalaqat");

                    b.Navigation("SupervisorAssignments");

                    b.Navigation("TeacherAttendances");
                });

            modelBuilder.Entity("KhairAPI.Models.Entities.Student", b =>
                {
                    b.Navigation("Attendances");

                    b.Navigation("ProgressRecords");

                    b.Navigation("StudentHalaqat");

                    b.Navigation("Target");
                });

            modelBuilder.Entity("KhairAPI.Models.Entities.Teacher", b =>
                {
                    b.Navigation("HalaqaTeachers");

                    b.Navigation("ProgressRecords");

                    b.Navigation("StudentHalaqat");

                    b.Navigation("TeacherAttendances");
                });

            modelBuilder.Entity("KhairAPI.Models.Entities.User", b =>
                {
                    b.Navigation("HalaqaAssignments");

                    b.Navigation("Teacher");
                });
#pragma warning restore 612, 618
        }
    }
}
